AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for the demo application.
Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 Bucket for viewing the files.
    Default: stratospheric-demo-bucket
Resources:
  FileBucket:
    Type: AWS::S3::Bucket
    DependsOn:
     - FileSyncQueuePolicy
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt FileSyncQueue.Arn
  FileSyncQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: stratospheric-demo-queue
  FileSyncQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref FileSyncQueue
      PolicyDocument:
        Statement:
          - Sid: Allow S3 access to queue
            Effect: Allow
            Action:
              - SQS:SendMessage
            Resource: !GetAtt FileSyncQueue.Arn
            Principal:
              AWS: '*'
            Condition:
              ArnLike:
                aws:SourceArn: !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref BucketName
