AWSTemplateFormatVersion: '2010-09-09'
Description: A stack that creates messaging infrastructure
Resources:
  TodoSharingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: stratospheric-todo-sharing
      MessageRetentionPeriod: 1209600 # 14 days maximum
      VisibilityTimeout: 300 # 5 minutes
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt 'TodoSharingDeadLetterQueue.Arn'
        maxReceiveCount: 3

  TodoSharingDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: stratospheric-todo-sharing-dead-letter-queue
      MessageRetentionPeriod: 1209600 # 14 days maximum

Outputs:
  TodoSharingQueueArn:
    Description: Arn of the TodoSharing Queue
    Value: !GetAtt 'TodoSharingQueue.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'TodoSharingQueueArn' ] ]
  StackName:
    Description: The name of this stack
    Value: !Ref 'AWS::StackName'
